### ISSUE TITLE
Wrong Version Alert

### ISSUE THREAD

**Issue by ItsEtc** [itscrystalline/IW2THs-Shortbows#1]
I installed version 1.1.0 patch 1 for fabric and the mod keeps telling me that I have the outdated version of the mod and tells me to update the mod from version 1.1.0 patch 1 fabric to version 1.1.0 patch 1 fabric, is there a way to fix this? Thanks a lot :)

**Comment by ItsEtc** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/111157453/185178965-63f2393b-ab3b-44d2-adeb-1e44ea8a8125.png">

This is the prompt i get

**Comment by itscrystalline** [comment]
There definitely is a fix, It was an oversight when I was coding the version mismatch detection system.
[Version 1.1.0-patch2](https://github.com/MyNameTsThad/IW2THs-Shortbows/releases/tag/1.1.0-patch2) should fix it for all versions.
